unbound_server:
  port: 3000
  db:
    type: postgres
    port: 5432
    user: postgres
    password: 123456
    # host: unbound.c410shmahqqg.ap-northeast-1.rds.amazonaws.com
    host: localhost
    name: unbound

  lang: zh
